### ISSUE TITLE
SSL Certificate issue - NET::ERR_CERT_AUTHORITY_INVALID and unable to advance to page

### ISSUE THREAD

**Issue by jacderida** [maidsafe/safe-build-infrastructure#81] opened 2019-06-10 12:36 UTC
We have seen that when an environment is re-provisioned, the SSL certificate doesn't seem to work correctly. On prod it appears like an unsigned SSL certificate, and on staging with the self-signed cert, you don't seem to be able to hit the environment. I did reproduce this on the staging environment, but I don't yet know what causes it.

**Comment by jacderida** [comment] 2019-06-10 19:28
When I was creating the QA environment today, I wasn't able to reproduce this issue. I think it might be caused by the reboot of the machines at the end, which I've disabled for now. Need to re-enable and see if I can reproduce.

**Comment by S-Coyle** [comment] 2019-06-11 16:27
@jacderida 
On latest master I switched QA env to use production LE, then tested the following scenarios:
1. Provision QA env, no `reboot_all_instances.sh` - all fine, ssl certificate is valid.
2. Re-provision QA env, no `reboot_all_instances.sh` - all fine, ssl certificate is valid.
3. Re-provision QA env, this time add `reboot_all_instances.sh` - all fine, ssl certificate is valid.
4. Re-provision QA env for a 3rd time, again with the `reboot_all_instances.sh` running (for 2nd time) - all fine, ssl certificate is valid.

Unable to reproduce this issue so looks like it may have been fixed by the addition of SSL cert generation idempotency here https://github.com/maidsafe/safe-build-infrastructure/issues/75.

If you're satisfied with this I'll let you close the issue

**Comment by S-Coyle** [comment] 2019-06-12 09:38
Confirmed with Chris that he was happy with this

**Closed as completed by S-Coyle** 2019-06-12 09:38 UTC
Labels: bug, infrastructure

**Comment by S-Coyle** [comment] 2019-06-12 14:18
Seem to have inadvertently reproduced this - steps to reproduce:
1. Provisioned QA env with prod LE server so it had a valid ssl cert.
2. Destroyed QA env.
3. Next day I provisioned QA env with staging LE server getting the error below on Chrome:
![image](https://user-images.githubusercontent.com/37112040/59358691-ee6d7280-8d24-11e9-9d16-c9a8951f6497.png)

Tried on Firefox and Chrome incognito and they allow me to advance to the site so the issue seems to be with browser cache from switching to prod LE then to staging

Emptied Chrome cache & hard reloaded - now able to access again on Chrome.
